'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.3082
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class Wfrm_PantallaCapturaISAAR

    '''<summary>
    '''Control lblTitle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control btnNuevo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnNuevo As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control gdnivel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents gdnivel As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Control pgareas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents pgareas As Global.DevExpress.Web.ASPxTabControl.ASPxPageControl

    '''<summary>
    '''Control lbltipo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbltipo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt11.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt11 As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Control lblnombre1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnombre1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt12.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt12 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblnombre2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnombre2 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt13.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt13 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblnombre3.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnombre3 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt14.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt14 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblnombre4.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnombre4 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt15.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt15 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblnombre5.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnombre5 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt16.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt16 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblfechaexistencia.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblfechaexistencia As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt21.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt21 As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Control lblhistoria.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblhistoria As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt22.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt22 As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''Control lbllugar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbllugar As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt23.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt23 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lbllugar0.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbllugar0 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt24.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt24 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblfoa.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblfoa As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt25.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt25 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblafl.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblafl As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt26.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt26 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lbleig.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbleig As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt27.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt27 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblcg.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblcg As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt28.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt28 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control aspxgdisaarrelacion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aspxgdisaarrelacion As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Control lblira.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblira As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt41.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt41 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblii.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblii As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt42.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt42 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblryo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblryo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt43.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt43 As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''Control lblee.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblee As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt44.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt44 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lblnd.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblnd As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt45.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt45 As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''Control lbl46.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl46 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt46.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt46 As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

    '''<summary>
    '''Control lbl47.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl47 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt47.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt47 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control lbl48.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl48 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt48.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt48 As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''Control lbl49.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbl49 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control txt49.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents txt49 As Global.DevExpress.Web.ASPxEditors.ASPxMemo

    '''<summary>
    '''Control btnguardar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnguardar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control lblidNorma.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidNorma As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control ASPxError.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ASPxError As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblidISAAR.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidISAAR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control ListaISAAR.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ListaISAAR As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control Relaciones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Relaciones As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control ListaCatalogoNaturaleza.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ListaCatalogoNaturaleza As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
