'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5448
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class wfrmQuery

    '''<summary>
    '''Control lbltitulo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbltitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control Regresar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Regresar As Global.DevExpress.Web.ASPxEditors.ASPxHyperLink

    '''<summary>
    '''Control lblTitle.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control trFiltrosBotones.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents trFiltrosBotones As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''Control butEjecutar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butEjecutar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control btnEditar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnEditar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control butGuardarFiltro.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butGuardarFiltro As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control butCancelar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butCancelar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control btnAgregar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnAgregar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control butGuardaFiltrosEditados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butGuardaFiltrosEditados As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control btnBorrar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnBorrar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control BtnPI.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents BtnPI As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control BtnPD.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents BtnPD As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control btnY.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnY As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control btnO.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents btnO As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control lblerror.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblerror As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblLbSQLDesc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblLbSQLDesc As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblHeadArchivo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblHeadArchivo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblArchivo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblArchivo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblHeadNivel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblHeadNivel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblNivel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblNivel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblHeadTipoExpediente.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblHeadTipoExpediente As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblSerie.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblSerie As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control tableFiltros.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tableFiltros As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lblIndiceDesc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblIndiceDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblOperadorDesc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblOperadorDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblvalores.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblvalores As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblIndice.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblIndice As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lbCampos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbCampos As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Control LbOperador.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LbOperador As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''Control lblOperador.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblOperador As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblFiltroEdited.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblFiltroEdited As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control val1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents val1 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control CampoSI_NO1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoSI_NO1 As Global.Portalv9.CampoSI_NO

    '''<summary>
    '''Control CampoFecha1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoFecha1 As Global.Portalv9.CampoFecha

    '''<summary>
    '''Control CampoPeriodoAno1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoPeriodoAno1 As Global.Portalv9.CampoPeriodoAno

    '''<summary>
    '''Control CampoPeriodoFechas1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoPeriodoFechas1 As Global.Portalv9.CampoPeriodoFechas

    '''<summary>
    '''Control CampoPeriodoMesAno1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoPeriodoMesAno1 As Global.Portalv9.CampoPeriodoMesAno

    '''<summary>
    '''Control CampoCatalogo1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents CampoCatalogo1 As Global.Portalv9.CampoCatalogo

    '''<summary>
    '''Control b_A.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents b_A As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Control nvalores2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents nvalores2 As Global.DevExpress.Web.ASPxEditors.ASPxListBox

    '''<summary>
    '''Control Y.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Y As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control B_E.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents B_E As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''Control val2.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents val2 As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

    '''<summary>
    '''Control butFiltroGrabar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butFiltroGrabar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control butFiltroCancelar.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents butFiltroCancelar As Global.DevExpress.Web.ASPxEditors.ASPxButton

    '''<summary>
    '''Control tableContultas.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tableContultas As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''Control lbSQLDesc.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lbSQLDesc As Global.DevExpress.Web.ASPxEditors.ASPxListBox

    '''<summary>
    '''Control ASPxGridView1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Control LBSQL.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents LBSQL As Global.DevExpress.Web.ASPxEditors.ASPxListBox

    '''<summary>
    '''Control lstFiltros.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lstFiltros As Global.DevExpress.Web.ASPxEditors.ASPxListBox

    '''<summary>
    '''Control dsIndices.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dsIndices As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control ObjConsulta.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents ObjConsulta As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control daOperadores.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents daOperadores As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control MsgBox1.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents MsgBox1 As Global.MsgBox.MsgBox
End Class
