'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5448
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class CampoGridUnbound

    '''<summary>
    '''Control tdCampo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tdCampo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Control Campo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Campo As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control tdTexto_Padres.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents tdTexto_Padres As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Control Texto_Padres.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents Texto_Padres As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control aspxGridCatalogoCampos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents aspxGridCatalogoCampos As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''Control dsListaCatalogo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dsListaCatalogo As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control dsCatalogoDatos.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dsCatalogoDatos As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control dsCatalogoDatosAll.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dsCatalogoDatosAll As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control dsValores.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents dsValores As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''Control lblidArea.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidArea As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblidElemento.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidElemento As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblidIndice.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidIndice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblidDescripcion.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidDescripcion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblidNivel.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblidNivel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblIndice_Tipo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblIndice_Tipo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblCatalogo.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblCatalogo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Control lblTipoValor.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblTipoValor As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblValores_Aceptados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblValores_Aceptados As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''Control lblValoresAgregados.
    '''</summary>
    '''<remarks>
    '''Campo generado automáticamente.
    '''Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    '''</remarks>
    Protected WithEvents lblValoresAgregados As Global.DevExpress.Web.ASPxEditors.ASPxLabel
End Class
