'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4216
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class CampoPeriodoMesAno

    '''<summary>
    '''tdCampo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCampo As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Campo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Campo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''tdTexto_Padres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdTexto_Padres As Global.System.Web.UI.HtmlControls.HtmlTableCell

    '''<summary>
    '''Texto_Padres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Texto_Padres As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''vAno_ini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAno_ini As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''vMes_ini control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMes_ini As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''vAno_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vAno_fin As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

    '''<summary>
    '''vMes_fin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vMes_fin As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit
End Class
